Adding homework 4
dzmitrybetska/dzmitry-repository pull request #5
Opened 2023-02-12 18:02 UTC by dzmitrybetska

2023-02-20 12:40 UTC, Willynick requested changes

2023-02-20 12:40 UTC, Willynick commented on Itacademycourses/src/by/itacademy/courses/hw4/Task5.java
> +        for (int i = 0; i < myArray.length; i++) {
i % 2 можно вынести в for.
По типу i = i + 2

2023-02-20 12:40 UTC, Willynick commented on Itacademycourses/src/by/itacademy/courses/hw4/Task2.java
> +            sum += digit % 10;
Операция digit % 10 происходит два раза. Чтобы это исключить - можно сохранить её в отдельную перемнную и затем использовать эту переменную уже

2023-02-20 12:41 UTC, Willynick requested changes

2023-02-20 12:41 UTC, Willynick commented on Itacademycourses/src/by/itacademy/courses/hw4/Task8.java
> +        for (int i = 000001; i < 1000000; i++) {
Можно начинать считать от большего числа, т.к. понятно, что первые числа не будут подходить нашему условию

2023-02-21 20:46 UTC, dzmitrybetska commented on Itacademycourses/src/by/itacademy/courses/hw4/Task5.java
> +        for (int i = 0; i < myArray.length; i++) {
Здорово, почему я не додумался?!?

2023-03-02 12:01 UTC, Willynick commented on Itacademycourses/src/by/itacademy/courses/hw4/Task8.java
> +        for (int i = 000001; i < 1000000; i++) {
Здесь я не совсем то имел ввиду, но ладно)

2023-03-02 12:01 UTC, merged